import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/adams-creation/background.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/adams-creation/character.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/austrian-painter/background.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/austrian-painter/character.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/battle-of-hu-lao-gate-2/background.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/battle-of-hu-lao-gate-2/character.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/boxing/background.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/boxing/character.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/moses/background.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/first-Sequence/moses/character.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/three-kingdom/background.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/three-kingdom/character.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/abraham/background.jpeg" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/abraham/character.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/adam-eve/background.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/adam-eve/character.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/leonardo/background.jpg" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/leonardo/character.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/mlk/background.png" />
        <link rel="preload" as="image" href="/preloader/preloader-images/second-Sequence/mlk/character.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} transition-all duration-1000 antialiased`}
        id="page-container"
      >
        {children}
      </body>
    </html>
  );
}
