/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\adameve_env.gltf -T 
Files: .\adameve_env.gltf [114.52KB] > D:\Wannabe Stuff\Projects\Monyet\AdamEveEnv\adameve_env-transformed.glb [55.51MB] (-48373%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useControls } from "leva";

export default function AdamEveEnv(props) {
  const { scene } = useGLTF("/adameve_env-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  const { spot1, spot2 } = useControls({ spot1: 500, spot2: 20 });

  return (
    <group {...props} dispose={null} receiveShadow={true}>
      {/* <directionalLight
        intensity={2}
        decay={2}
        castShadow={true}
        position={[2.599, 2.582, 3.344]}
        rotation={[-0.615, 0.705, -0.774]}
        target={nodes.Sun.target}
      >
        <primitive object={nodes.Sun.target} position={[0, 0, -1]} />
      </directionalLight> */}
      <spotLight
        intensity={spot1}
        angle={1.221}
        penumbra={0.15}
        decay={2}
        castShadow={true}
        position={[5.295, 2.596, 4.506]}
        rotation={[-0.565, 0.785, 0.918]}
        target={nodes.Spot.target}
      >
        <primitive object={nodes.Spot.target} position={[0, 0, -1]} />
      </spotLight>
      <spotLight
        intensity={spot2}
        angle={0.698}
        penumbra={0.15}
        decay={2}
        castShadow={true}
        position={[6.314, 0.198, -0.42]}
        rotation={[3.065, 1.506, -2.541]}
        target={nodes.Spot001.target}
      >
        <primitive object={nodes.Spot001.target} position={[0, 0, -1]} />
      </spotLight>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.002"]}
        scale={[2.5, 4.29, 1.5]}
      />
      <mesh
        geometry={nodes.Weird_Tree_Trunk_in_Forest.geometry}
        material={materials.Lighthouse_forest_3_u1_v1}
        position={[0.579, -0.047, 0.836]}
        scale={0.241}
      />
      <mesh
        geometry={nodes.Granite_Rock_Photoscan.geometry}
        material={materials.lynn_mar624_7_u1_v1}
        position={[0.325, 0, -0.93]}
        scale={0.213}
      />
      <mesh
        geometry={nodes.pine_roots_a001.geometry}
        material={materials["pine_roots_a.001"]}
        position={[1.705, 0.014, -0.62]}
        rotation={[Math.PI, -1.559, Math.PI]}
      />
      <mesh
        geometry={nodes.pine_roots_b001.geometry}
        material={materials["pine_roots_b.001"]}
        position={[0.729, 0.024, 0.663]}
        scale={0.839}
      />
      <group
        position={[1.767, 0, -0.785]}
        rotation={[-Math.PI, -0.589, -Math.PI]}
        scale={0.796}
        receiveShadow={true}
      >
        <mesh
          geometry={nodes.island_trees_01_blockout_cleaned001.geometry}
          material={materials["island_tree_01_leaves.001"]}
        />
        <mesh
          geometry={nodes.island_trees_01_blockout_cleaned001_1.geometry}
          material={materials["island_tree_01_branches.001"]}
        />
        <mesh
          geometry={nodes.island_trees_01_blockout_cleaned001_2.geometry}
          material={materials["island_tree_01.001"]}
        />
      </group>
      <mesh
        geometry={nodes.island_tree_02.geometry}
        material={materials.island_tree_02}
        position={[0.688, -0.008, -1.047]}
        scale={0.617}
      />
      <mesh
        geometry={nodes.nettle_plant_medium_a_LOD0.geometry}
        material={materials.nettle_plant}
        position={[0.4, 0, 0.782]}
        scale={3.455}
      />
      <mesh
        geometry={nodes.fern_02_a.geometry}
        material={materials.fern_02}
        position={[0, 0, 1]}
      />
      <group position={[1.362, 0, 1.034]} scale={0.138} receiveShadow={true}>
        <mesh
          geometry={nodes.tree016.geometry}
          material={materials.jacaranda_tree_leaves}
        />
        <mesh
          geometry={nodes.tree016_1.geometry}
          material={materials.jacaranda_tree_branches}
        />
        <mesh
          geometry={nodes.tree016_2.geometry}
          material={materials.jacaranda_tree_trunk}
        />
      </group>
      <mesh
        geometry={nodes.Plane027.geometry}
        material={materials.jacaranda_tree_branches}
      />
      <mesh
        geometry={nodes.Plane027_1.geometry}
        material={materials.jacaranda_tree_leaves}
      />
    </group>
  );
}

useGLTF.preload("/adameve_env-transformed.glb");
