/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\EGYPT.glb -T s 
Files: .\EGYPT.glb [2.42MB] > D:\Wannabe Stuff\Projects\Monyet\ADAM EVE & EGYPT\Compressed\EGYPT-transformed.glb [625.55KB] (74%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Egypt(props) {
  const { nodes, materials } = useGLTF("/EGYPT-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Realistic procedural Dune"]}
        scale={[2.5, 1, 1.5]}
      />
      <mesh
        geometry={nodes.Pyramid001.geometry}
        material={materials["Stone.001"]}
        position={[-1.059, 0, -2.334]}
        rotation={[0, -0.639, 0]}
        scale={1.994}
      />
    </group>
  );
}

useGLTF.preload("/EGYPT-transformed.glb");
