/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\EGYPT.glb -T s 
Files: .\EGYPT.glb [2.42MB] > D:\Wannabe Stuff\Projects\Monyet\ADAM EVE & EGYPT\Compressed\EGYPT-transformed.glb [625.55KB] (74%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function EgyptEnv(props) {
  const { nodes, materials } = useGLTF("/EGYPT-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <pointLight
        intensity={Math.PI * 10}
        decay={2}
        position={[4.076, 5.904, -1.005]}
        rotation={[-1.839, 0.602, 1.932]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pyramid001.geometry}
        material={materials["Stone.001"]}
        position={[-1.059, 0, -2.334]}
        rotation={[0, -0.639, 0]}
        scale={1.994}
      />
      <group position={[-0.424, -0.844, 0.805]} scale={[1.35, 4.162, 1.35]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002.geometry}
          material={materials["Procedural Clay.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_1.geometry}
          material={materials["Cactus.002"]}
        >
          <meshStandardMaterial color="#137504" />
        </mesh>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Empty001.geometry}
        material={materials.Empty}
        position={[-3.823, 1.457, -0.81]}
        rotation={[1.582, 0.182, -1.631]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sand_Dunes_in_Desert_Terrain.geometry}
        material={materials.WC_Terrain_0_0}
        scale={0.002}
      />
    </group>
  );
}

useGLTF.preload("/EGYPT-transformed.glb");
