/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\NEWYORK.glb -T --shadows -E 
Files: .\NEWYORK.glb [75.34MB] > D:\Wannabe Stuff\Projects\Monyet\NY\NEWYORK-transformed.glb [13.1MB] (83%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function NewYorkEnv(props) {
  const { nodes, materials } = useGLTF("/NEWYORK-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <pointLight
        intensity={Math.PI * 10}
        decay={2}
        position={[4.076, 5.904, -1.005]}
        rotation={[-1.839, 0.602, 1.932]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.PaletteMaterial001}
        scale={[2.5, 1, 1.5]}
      />
      <group scale={0.046}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials["Painted Rough Wall"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials["Concrete smooth"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_2.geometry}
          material={materials.Ground_large}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_3.geometry}
          material={materials.Concrete030_4K}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_4.geometry}
          material={materials["MDF Concrete metropolitan - Arauco"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_5.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_6.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_7.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_8.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_9.geometry}
          material={materials.direzione_obbligatoria}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_10.geometry}
          material={materials.metallo_palo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_11.geometry}
          material={materials.metallo_cerniere}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_12.geometry}
          material={materials.PaletteMaterial007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_13.geometry}
          material={materials.PaletteMaterial008}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_14.geometry}
          material={materials.PaletteMaterial009}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_15.geometry}
          material={materials.PaletteMaterial010}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_16.geometry}
          material={materials.PaletteMaterial011}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_17.geometry}
          material={materials["speedometer display plane.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_18.geometry}
          material={materials.PaletteMaterial012}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_19.geometry}
          material={materials["centre screen display plane.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_20.geometry}
          material={materials.PaletteMaterial013}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_21.geometry}
          material={materials["Plastic 01"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_22.geometry}
          material={materials["Wood dark"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_23.geometry}
          material={materials["Zinc steel 01 rough"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_24.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_25.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_26.geometry}
          material={materials.PaletteMaterial006}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_27.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/NEWYORK-transformed.glb");
