/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\WW2.glb -T --shadows -E 
Files: .\WW2.glb [240.85MB] > D:\Wannabe Stuff\Projects\Monyet\CHINA WW2\ww2\WW2-transformed.glb [20.11MB] (92%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function WW2Env(props) {
  const { nodes, materials } = useGLTF("/WW2-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <pointLight
        intensity={Math.PI * 10}
        decay={2}
        position={[4.076, 5.904, -1.005]}
        rotation={[-1.839, 0.602, 1.932]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Stone Flags or Bricks 8"]}
        scale={[2.5, 1, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder058.geometry}
        material={materials.Tank}
        position={[-3.506, 0.971, 6.526]}
        rotation={[Math.PI / 2, 0.238, 0]}
        scale={0.63}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder057.geometry}
        material={materials.belts}
        position={[2.446, 0.407, 6.521]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.291, 0.114, 0.291]}
      />
      <group position={[1.252, 0, 0.922]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.texturedMesh001.geometry}
          material={materials["material_1001.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.texturedMesh001_1.geometry}
          material={materials["material_1002.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.texturedMesh001_2.geometry}
          material={materials["material_1003.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.texturedMesh001_3.geometry}
          material={materials["material_1004.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.texturedMesh001_4.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-2.974, 0, 2.013]}
        rotation={[-Math.PI, 1.012, -Math.PI]}
        scale={0.306}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube136.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube136_1.geometry}
          material={materials.Concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube136_2.geometry}
          material={materials.windows}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Debris_of_bricks_and_a_wall001.geometry}
        material={materials["Debris of bricks and a wall.001"]}
        position={[-2.115, 0, -0.001]}
        rotation={[0, 1.239, 0]}
        scale={0.739}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Empty001.geometry}
        material={materials.Empty}
        position={[-15.229, 4.913, -0.811]}
        rotation={[1.555, 0.088, -1.591]}
        scale={2.785}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials.dark}
        position={[-0.181, 0.132, -0.618]}
        rotation={[0, -0.838, 0]}
        scale={0.129}
      />
      <group
        position={[-0.217, 0.224, -0.648]}
        rotation={[0, -0.838, 0]}
        scale={0.122}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials.star}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[-0.38, 0.315, -0.612]}
        rotation={[0, -0.838, 0]}
        scale={[0.009, 0.004, 0.012]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials["black "]}
        position={[-0.377, 0.322, -0.534]}
        rotation={[-0.062, -0.809, -1.494]}
        scale={0.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BodyAttachments.geometry}
        material={materials["Stryker Equipments"]}
        position={[1.524, 0.32, 0.897]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={0.209}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Front2L.geometry}
        material={materials.StrykerWheel}
        position={[1.539, 0.1, 0.625]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={0.209}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lights006.geometry}
        material={materials.StrykerLights}
        position={[1.522, 0.324, 0.899]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={0.209}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Strykerbody.geometry}
        material={materials.StrykerBody}
        position={[1.926, 0.139, 0.662]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={0.209}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Turret002.geometry}
        material={materials.StrykerTurret}
        position={[1.343, 0.413, 1.011]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={0.209}
      />
      <group
        position={[-3.111, -0.121, -1.502]}
        rotation={[0, -1.349, 0]}
        scale={0.18}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_1.geometry}
          material={materials["01___Default_1008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_2.geometry}
          material={materials["01___Default_1001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_3.geometry}
          material={materials["01___Default_1002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_4.geometry}
          material={materials["01___Default_1003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_5.geometry}
          material={materials["01___Default_1004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_6.geometry}
          material={materials["01___Default_1005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_7.geometry}
          material={materials["01___Default_1006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_8.geometry}
          material={materials["01___Default_1007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_9.geometry}
          material={materials["01___Default_1009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.defaultMaterial007_10.geometry}
          material={materials["01___Default_1010"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.model.geometry}
        material={materials.material_1}
        position={[-1.335, -0.06, -0.415]}
        scale={0.289}
      />
    </group>
  );
}

useGLTF.preload("/WW2-transformed.glb");
